### ISSUE TITLE
Create a test case to cover the redeploying of the etcd 

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#1002]
**Description**
Develop a test case to cover the following issue and list it under advanced dir
https://github.com/zero-os/0-orchestrator/issues/847

**Comment by Dinaamagdy** [comment]
## Scenario1
- kill etcd service  for n1
-  container  should  still up and the etcd service should  just restart again.
## scenario 2
- kill etcd container .
- the etcd service and container will just restart again
