### ISSUE TITLE
Make it possible to link a templatedisk with metadata

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#1005]
Currently we only support linking to a templatedisk by 1 single ardb server which shares metadata and data.

This has several dissadvantages: we cant specify a templatecluster existing out of multiple ardb nodes. We can't specify the required blocksize for this vdisk. We can't specify db indexes.

I would propase we replace the value of the templatevdisk with a http(s) url pointing to a yaml file containing the necesary information this format would be like described in https://github.com/zero-os/0-Disk/blob/master/docs/config.md#reading-data-1
Where only 1 disk is given and no zeroStorClusters or tlogServers are required.

**Comment by FastGeert** [comment]
@khaledkbadr don't start working on this. AFAIK we are gonna replace the template cluster mechanisme with importing templates locally. @zaibon please give the right instructions here.

**Comment by khaledkbadr** [comment]
FYI: Issue originally was a fix for #965 since we don't have anyway to know which blocksize that the template was built with and QA had a lot of trouble entering the wrong blocksize.

**Comment by zaibon** [comment]
Issue regarding the import of templates:
- https://github.com/zero-os/0-Disk/issues/460
- https://github.com/zero-os/0-Disk/issues/463

**Comment by FastGeert** [comment]
This has been solved in the 0-Disk project.
