### ISSUE TITLE
Body for storagcluster and vdisk post request  in raml not exist 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1011]
## Issue 

https://cdn.rawgit.com/zero-os/0-orchestrator/35f7c937/raml/api.html#storageclusters_post
https://cdn.rawgit.com/zero-os/0-orchestrator/35f7c937/raml/api.html#vdisks_post
body for post request doesn't exist as shown : 

![selection_537](https://user-images.githubusercontent.com/24386802/30315552-a9f7dae0-97a4-11e7-86ef-fba52acedb97.png)

**Comment by khaledkbadr** [comment]
fixed in https://github.com/zero-os/0-orchestrator/commit/025e6110a31e1d2943a7d45bcc4cfc819b626a37

**Comment by Dinaamagdy** [comment]
## Software Version 
https://github.com/zero-os/0-orchestrator/issues/1008
