### ISSUE TITLE
Add API to import vdisk template from 0-hub to local storage cluster

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#1014]
This relates to https://github.com/zero-os/0-Disk/issues/460

We need to add an API that allow to import a vdisk templates from the 0-hub.
I propose to add these endpoints:
`GET /storageclusters/{label}/templates` List the templates available in the storage cluster
`POST /storageclusters/{labe}/template` : Add an new templates to the storage cluster, the request will have the url of the 0-hub and the name of the templates to import.

**Comment by abdulrahmantkhalifa** [comment]
done in  https://github.com/zero-os/0-orchestrator/issues/1055
