### ISSUE TITLE
Start 0-stor without JWT authentification

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#1021]
Since the 0-stor used for the object storage cluster are not exposed to the public and only used internall for the storage system. I think it's safe to start the 0-stor servers with JWT authentification disabled.
The will simplify the configuration and deployment of the 0-stor servers greatly.

Depends on : https://github.com/zero-os/0-stor/pull/237

**Comment by FastGeert** [comment]
Won't fix
