### ISSUE TITLE
Fix Installer 

### ISSUE THREAD

**Issue by arahmanhamdy** [zero-os/0-orchestrator#1024]
#### Installation information
- orchestrator version: master
- jumpscale version: master
- operating system: ubuntu 16.04

#### Detailed description
The installer script stopped working after modifications for jumpscale:
https://github.com/Jumpscale/core9/commit/5b240b1dc5ecb9084cfb96afcadb0b0a3d689758

#### Steps to reproduce
run:
bash install-orchestrator.sh "$BRANCH" "$ZEROTIERNWID" "$ZEROTIERTOKEN" "$ITSYOUONLINEORG"

**Comment by zaibon** [comment]
@arahmanhamdy Please provide error messages and any information that can help to debug this.

**Comment by arahmanhamdy** [comment]
The issue was related to gopaths, Fixed:https://github.com/zero-os/0-orchestrator/commit/bf08c78a17da6302414a4830db00d614c8a953a7
