### ISSUE TITLE
VM doesn't boot after create it with block cluster only 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1057]
## Steps 
- Create block cluster 
```
{
	"label": "st",
	"servers": 1,
	"driveType": "hdd",
	"nodes": [
		"0cc47a740636"
	],
	"clusterType": "block"

}
```
- create vdisk with created cluster 
```
{
  "id": "vdisk2",
  "size": 15,
  "blocksize": 4096,
  "type": "boot",
  "templatevdisk": "ardb:///template:ubuntu-1604",
  "blockStoragecluster": "st"
}
```
- create vm with created vdisk 
```
{
	"id": "dinatest",
	"memory": 1024,
	"cpu": 1,
	"disks": [
		{
			"vdiskid": "vdisk2",
			"maxIOps": 2000
		}
	],
	"userCloudInit": null,
	"systemCloudInit": null
}
```
## Issue 
- try to login inside vm , will result no bootable device as shown 
![selection_548](https://user-images.githubusercontent.com/24386802/30586797-66ead95e-9d31-11e7-9637-0f7611587541.png)

## Software Version 
alpha8:a7ed0d5e0925d86bb95c95726eff3635efca7440

**Comment by zaibon** [comment]
@Dinaamagdy can you try with a real cluster. 
Object cluster is using erasure coding, so having a single server doesn't make sense.

**Comment by khaledkbadr** [comment]
related to https://github.com/zero-os/0-orchestrator/issues/1057

**Comment by Dinaamagdy** [comment]
@zaibon I tried it with 2 servers and same result, 
but actually I didn't use object cluster ,I'm using only block cluster

**Comment by zaibon** [comment]
> I didn't use object cluster ,I'm using only block cluster

Indeed sorry my bad didn't read your config properly

**Comment by Dinaamagdy** [comment]
## Sotware version 
ffcdcb98d4b9545a8d6b5ad0c5c45081075f8bca
