### ISSUE TITLE
VM create with a bad nic crashes too late

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-orchestrator#1091]
If you create a VM with a nic of type bridge that doesn't exist, it won't immediately return a bad request, it will start creating the service and crash while installing it and return a bad request then after the service has been created even though it failed to create the VM on the node. 
The bad request should be returned at an earlier stage before attempting to create the VM.

**Comment by ahmedelsayed-93** [comment]
### software version
master : 851d41fa
