### ISSUE TITLE
Make the encryption key for vdisk import optional

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#1101]
Since this commit : https://github.com/zero-os/0-Disk/commit/fad3a45dec14ca0eb582fa5ace6d6496e80c1faa

The encryption key for import/export vdisk is optional and the key changed from a positional argument to a flag. 

We need to update our code to support the new format of the command.

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 851d41fa
