### ISSUE TITLE
Direct access api requests return 500 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1110]
## Issue 
- any direct access api  request doesn't work as shown 
![selection_554](https://user-images.githubusercontent.com/24386802/30963541-1c7712e2-a44e-11e7-8201-9ffa342bcc68.png)
## Software Version 
jumpscale: master
0-orchestrator : 7e630356cbd56f75ca5debc8b0b47f7902732c18

**Comment by FastGeert** [comment]
@Dinaamagdy can you please add the cli parameters with which the orchestrator was running & the organization with which your nodes are booted.

**Comment by Dinaamagdy** [comment]
## Software Version 
931b4165e1240a0838622ad3fa83f75230e85580
