### ISSUE TITLE
Orchestrator server doesn't start Using installation script 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1134]
## Steps 
use installation script https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh to install orchestrator inside js9 docker 
## Issue 
After installation finished ,orchestrator server didn't start as shown
![selection_558](https://user-images.githubusercontent.com/24386802/31067438-3a8b417e-a753-11e7-86b1-74ec3b36ed5e.png)

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 851d41fa
