### ISSUE TITLE
Get Image api doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1148]
## Steps 
- Create Storage cluster
- create vdisksorage vds1
- create image1 for vds1
- create image2 for vds1
## Issue 
- try to get images list with 
```/vdiskstorage/{vdiskstorageid}/images``` Api
will get list of two images but with same name 
![selection_559](https://user-images.githubusercontent.com/24386802/31083240-746ceeea-a791-11e7-88fd-6de9911bbf19.png)

- try to get any image of them using 
```/vdiskstorage/{vdiskstorageid}/images/imageid``` Api
it will result not found with status code 404 as shown 
![selection_560](https://user-images.githubusercontent.com/24386802/31083312-b309a238-a791-11e7-8f8a-9c45bb858d38.png)
## Software Version 
016ec72ed0b94ed4e2c7cfa2ffc0749c06190d16

**Comment by ahmedelsayed-93** [comment]
### software version
master : 851d41fa
