### ISSUE TITLE
Bad json output

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#1153]
![image](https://user-images.githubusercontent.com/15246294/31114807-10c4254a-a820-11e7-9915-4177d8bd8f6d.png)

**Comment by serboctor** [comment]
@FastGeert I tried the same payload and it works fine with me without `internal server error` part. Any extra info to help me reproduce this?

**Comment by FastGeert** [comment]
while the import is going, delete the service in ays

**Comment by serboctor** [comment]
I can't reproduce it, I don't get a bad json, I get a normal 500 with one json.
![image_post_delete](https://user-images.githubusercontent.com/6323012/31229645-b752fd1a-a9e1-11e7-923b-8a656130bccc.png)
