### ISSUE TITLE
All Vdiskstorages  have same imported images 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1156]
## Steps 
- create storagecluster
- create vdiskstorage1 
- import image1 and image2 in vdiskstorage1
- Create vdiskstorage2

## Issue 
list images in vdiskstorage2  , you will find the two images which created in vdiskstorage1

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 851d41fa
