### ISSUE TITLE
Test case:Verify containers' PUT REST API

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#1177]
**Description**
Develop a test case to verify contaners' put rest api.

**Test case pass condition**
This test case should only be passed if we can update the container data using the PUT method.

**Comment by john-kheir** [comment]
@islamTaha12 This test case is implemented here: GAT-141 ..extend_tests.test01_containers_apis.py.TestcontaineridAPI.test018_attach_different_nics_to_same_container

**Comment by islamTaha12** [comment]
@john-kheir 
I checked this test case. I think we need to make sure that updating the nics will be working well too not just list it. 

I think it would be nice if we update it to be like this:
- Create container_1
- Add a bridge_1 to it
- List nics, should only have bridge_1
- Ping google.com, should succeed
- Update the nics to be connected with bridge_2
- List nics, should only have bridge_2
- Ping google.com, should succeed
