### ISSUE TITLE
After Create nodes services ,all nodes jobs cancelled and nodes unauthorized 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1179]
## Steps 
- install ays9 from master 
- install orchestrator from master 
- run configuration and bootstrap blueprints
## Issue 
- After create node services ,nodes unauthorized  again, and all node jobs cancelled as shown 
![selection_563](https://user-images.githubusercontent.com/24386802/31331012-e9bc295a-ace0-11e7-9ca9-6f7eb110ab28.png)

**Comment by rkhamis** [comment]
@Dinaamagdy please validate that this is no longer the issue after the merge

**Comment by Dinaamagdy** [comment]
##Software version 
931b4165e1240a0838622ad3fa83f75230e85580
