### ISSUE TITLE
Ays consume much time in  failure request 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1184]
Ays now took much time to retry the request which fail at first , is that normal behaviour  ?

**Comment by rkhamis** [comment]
What happens is that it will retry it 6 times. The wait time for each retry increases on every retry.
So it takes about 46min 10secs  + action time to finish all retries.

**Comment by zaibon** [comment]
Related to https://github.com/Jumpscale/ays9/issues/267

**Comment by serboctor** [comment]
@Dinaamagdy  this can now be configured, please check https://github.com/zero-os/0-orchestrator/blob/master/docs/running/README.md
