### ISSUE TITLE
in watchdog filter on important nbdserver messages only

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#1206]
Right now we call the watchdog handler on every single nbdserver message, we need to filter on the messages we only want to act upon.

This was addressed in a review in this pull request, but got merged anyway with comment to be addressed in another pr

https://github.com/zero-os/0-orchestrator/pull/1182

**Comment by zaibon** [comment]
@khaledkbadr you seems to know what to do, send the PR

**Comment by khaledkbadr** [comment]
The description is in the issue, I don't know the messages that we're waiting for from the nbdserver. So whoever is fixing that maybe needs to research or ask the author of the code

**Comment by zaibon** [comment]
@muhamadazmy can you check this. Seems you're the last one to change this line and worked on the sefl-healing of the storage

**Comment by muhamadazmy** [comment]
Thanks @khaledkbadr for catching this. Indeed we are only interested in the messages of level `20`, I believe this is supported by the watchdog, no?

Should I do it, or u do it?

**Comment by khaledkbadr** [comment]
Right now I'm working on another issue, and you seem to know which messages do you want to exactly listen to. if you're free, it's yours :D
