### ISSUE TITLE
container_apis: get container disks return 404 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1209]
### Scenario 
- Create container
- send api request to api ```/nodes/{nodeid}/containers/{containername}/disks``` to get container disks 

![image](https://user-images.githubusercontent.com/24386820/31584446-246ab0da-b1af-11e7-82b0-f08cb2b3fdf4.png)

![image](https://user-images.githubusercontent.com/24386820/31584450-344aa8fc-b1af-11e7-8d61-a8c34c06658e.png)

**Comment by serboctor** [comment]
There is no such thing as container disks. I removed it from the api.html file and cleaned up the old commented code.

**Comment by ahmedelsayed-93** [comment]
### software version 
master : 851d41fa
