### ISSUE TITLE
delete non-existing vdisk returns 204 instead of 404

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1274]
### API
```DELETE vdiskstorage/f0e81e9c57/vdisks/fake_vdisk```

### request && response
![image](https://user-images.githubusercontent.com/24386820/31943445-14a47e62-b8c9-11e7-9183-0d730a9dc40c.png)

### expected response
404

### software version
master : 7c79c26

**Comment by serboctor** [comment]
This is by design, please check https://github.com/zero-os/0-orchestrator/pull/1186
