### ISSUE TITLE
Test Cases: We need to cover /health api

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#1291]
We need to cover /health api
![image](https://user-images.githubusercontent.com/17981089/32142493-b52338a8-bca0-11e7-8e70-5e16eddf3267.png)

**Comment by Dinaamagdy** [comment]
Redirect to this tasks : 
https://github.com/zero-os/0-orchestrator/issues/1322
https://github.com/zero-os/0-orchestrator/issues/1321
https://github.com/zero-os/0-orchestrator/issues/1317
https://github.com/zero-os/0-orchestrator/issues/1319
https://github.com/zero-os/0-orchestrator/issues/1320
