### ISSUE TITLE
Make the ays retries globally configurable from the orchestrator apis

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-orchestrator#1308]
Currently, the orchestrator API waits for all 6 retries before returning the result in case of a failing API.
AYS exposes the ability to configure the number of retries and configure the delay between the retries. 
Make the retries configurable from the API, this will be a global configuration that will be applied to all runs.

**Comment by ahmedelsayed-93** [comment]
### software version
master 5c7668358
