### ISSUE TITLE
GET  /health/storageclusters Api doesn't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#1309]
## Steps 
- try GET  /health/storageclusters Api 
## issue 
Will throw this error 
![selection_568](https://user-images.githubusercontent.com/24386802/32219780-087a7f50-be38-11e7-88f4-b3c12c19ba1f.png)
##  0-orchestrator error
```
ERRO[5305] json: cannot unmarshal string into Go value of type []client.ServiceData 

```
## Software version 
1d03ac6ba39ceb325d06469cbaf22e0ecd9ef341

**Comment by ahmedelsayed-93** [comment]
### software version
master : 851d41fad
