### ISSUE TITLE
get dashboard with fake graph id returns 200 instead of 404

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1312]
### API
```
GET  /graphs/{graphid}/dashboards/{dashboardname}
```
### request and response
![image](https://user-images.githubusercontent.com/24386820/32224820-a2881a54-be4b-11e7-85b1-17523b70f975.png)

### software version
master : 7c79c26

**Comment by ahmedelsayed-93** [comment]
issue still exists 
### expected response 
response code should be 404
### actual response
![image](https://user-images.githubusercontent.com/24386820/32767413-fbdd1df4-c91b-11e7-9c9a-3ce9db468601.png)
response code 200 with empty list in body

### software version
master : 851d41fa

**Comment by serboctor** [comment]
> issue still exists

The ticket was opened for `GET  /graphs/{graphid}/dashboards/{dashboardname}` not `GET  /graphs/{graphid}/dashboards`. However, I fixed the other one now. Please check again.
