### ISSUE TITLE
healthcheck apis : nodes status is always skipped

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#1332]
### API
```GET  /health/nodes```
### Environment 
```be-scale-2```

### request and response
![image](https://user-images.githubusercontent.com/24386820/32320800-a2e8da7e-bfc7-11e7-9679-a909de05b387.png)

### software version
master 68517321

**Comment by serboctor** [comment]
Status 'SKIPPED' means that one or more of this node's healthchecks were skipped which is an acceptable result since some healthchecks(fan, powersupply and temprature) are skipped when there is no available info.

**Comment by serboctor** [comment]
After reviewing the specs with @zaibon and @grimpy, we agreed to display SKIPPED only if ALL healthchecks for this node were skipped. However, the behavior will remain the same for the WARNING and ERROR, if one or more healthchecks have either statuses, it will be displayed in `GET /health/nodes` with ERROR having a higher priority.
