### ISSUE TITLE
Need delete on Node in grid api

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#160]

**Comment by Dinaamagdy** [comment]
can't verfiy till this  issue  https://github.com/Jumpscale/jumpscale_core8/issues/897  solved

**Comment by Dinaamagdy** [comment]
the deleted node return again to node list as bootstrap blueprint will  authenticate it again because it doesn't deleted from zerotier network 
## SV: 
e1bb4cbe0cf7014f9606efac58d12331fa635694

**Comment by serboctor** [comment]
From the portal, when a node is deleted, it is hidden AND banned so it can't rejoin. The api exposes a functionality to hide the members, but it doesn't expose a ban functionality.

**Comment by Dinaamagdy** [comment]
### software version
master : ebd22d1
