### ISSUE TITLE
storagepools_apis: get storagepool devices returns devices with empty uuid

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#209]
### API
```nodes/{{nodeid}}/storagepools/{{storagepoolname}}/devices```

### request and response
![image](https://cloud.githubusercontent.com/assets/24386820/25946626/4b8bc520-364c-11e7-9c29-7cc6e16250ba.png)

**g8os client**
![image](https://cloud.githubusercontent.com/assets/24386820/25946649/675a07ee-364c-11e7-98fc-2c73c73070af.png)

### SV
js 4a39bad
resourcepool 02c0ebf

**Comment by grimpy** [comment]
Can't reproduce this one

![170511_133458](https://cloud.githubusercontent.com/assets/143869/25947232/ca97fefe-364e-11e7-9e18-689c48ddba88.png)

**Comment by ahmedelsayed-93** [comment]
can reproduce it with latest software versions 
jumpscale  4a39bad
resourcepool 60c9e8f

![image](https://cloud.githubusercontent.com/assets/24386820/25948945/162fc7a0-3656-11e7-8315-d27b9e362722.png)

**Comment by ahmedelsayed-93** [comment]
issue still exists

![image](https://cloud.githubusercontent.com/assets/24386820/26033261/cf4a3faa-38a8-11e7-9caa-5149e42880cb.png)

![image](https://cloud.githubusercontent.com/assets/24386820/26033273/12da1cea-38a9-11e7-8f65-18f0c44037be.png)

### SV
js f8944db
resourcepool a30a8b4

**Comment by serboctor** [comment]
I couldnt reproduce it. However, it takes a second for the uuid to reflect.
![devices](https://cloud.githubusercontent.com/assets/6323012/26106975/17fbdf60-3a48-11e7-839c-ed6506b26848.png)

**Comment by serboctor** [comment]
lsblk sometimes doesnt return partuuid for partitions even though they clearly have a partuuid when I check /dev/disk/by-partuuid/. This results in the values being empty also in client.disk.list() and eventually remain empty in ays services.

**Comment by john-kheir** [comment]
This issue is still there
![sssss](https://cloud.githubusercontent.com/assets/15011431/26404899/c5f1052c-4093-11e7-80b8-06cc0cbbbc98.png)
### Version
rp-v: e1bb4cbe0cf7014f9606efac58d12331fa635694

**Comment by serboctor** [comment]
For this, the update doesnt happen instantly. It takes a couple of seconds or so, and after that youll find that the device changed into a partition and the uuid will appear. If the device didnt change into a partition then that means something in the action failed and it is not just a uuid problem anymore.
Please make sure you give it enough time and if there is an error in ays, paste it here because other wise debugging becomes impossible.

**Comment by ahmedelsayed-93** [comment]
![image](https://user-images.githubusercontent.com/24386820/28009510-004e1b3c-655c-11e7-90ee-64a531f1ebe1.png)

### software version
master : 8e16c6a1

**Comment by serboctor** [comment]
Tested it on local setup and on be-g8-3 and it works fine.

**Comment by Dinaamagdy** [comment]
## Software Version 
67468454713d48e2e4a17bdee3fbe6e1c41e2080
