### ISSUE TITLE
Implement cloud-init-server ays service

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#245]
Cloud-init-server hosts 
Stores cloud-init data and serves it over http

**Comment by Dinaamagdy** [comment]
##  Steps
- make gateway with cloudinit as shown

![image](https://user-images.githubusercontent.com/24386802/26931584-43a4a5cc-4c61-11e7-8091-9114aedea782.png)
- create vm with this gateway : 
- check hostname which should be as we set in cloud int

## Issue 
cloud init doesn't work as hostname doesn't change in created vm

![image](https://user-images.githubusercontent.com/24386802/26931558-2f21102c-4c61-11e7-976a-2fdfd7f6f4e1.png)
``

**Comment by FastGeert** [comment]
@Dinaamagdy, check the cloudinit documentation on 0-chestration branch. You need to send YAML instead of json. This was changed later on.

**Comment by Dinaamagdy** [comment]
I tried it with another configuration using yaml ,and also doesn't work 
![selection_410](https://user-images.githubusercontent.com/24386802/26934844-c45be15e-4c6a-11e7-866f-9e530be6b056.png)

**Comment by grimpy** [comment]
@FastGeert yaml is a superset of json, aka json is valid yaml, so sending json works fine.

**Comment by Dinaamagdy** [comment]
it  doesn't work with  "ardb://hub.gig.tech:16379/template:ubuntu-1604" template

**Comment by grimpy** [comment]
its not supposed to work with that image, Ill make sure there is atleast one test image is available

**Comment by grimpy** [comment]
new template was uploaded please test with it "ardb://hub.gig.tech:16379/template:ovc:ubuntu-1604"

**Comment by Dinaamagdy** [comment]
## Software Version 
bfe4e6da50f88c5a471c31953c0fb8175f3ce3c0
