### ISSUE TITLE
"201 created" response when creating bridge with the same params more than one time

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#266]
When creating a bridge more than one time with the same parameters, we got "201 created" response
Actually the bridge wasn't created but at least we need a different response that this bridge is already there on the system
![reopen](https://cloud.githubusercontent.com/assets/15011431/26351320/78e8ccf6-3fb7-11e7-942e-19d22925fad0.png)

## Versions
Verified on 
core0-v: master c1513139664d3e782ddc72b8ea65c7376e11b19e
resourcepool-v: master  10a8901f3a26e9ee6275c322bf32307f4c2ed84f

**Comment by Dinaamagdy** [comment]
## SV
ae80985db3de3b9a2a77fc1f18ad889d71ef21ee
