### ISSUE TITLE
Adapt performance test script to new nbd server configuration

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#267]
Fix and adapt the performance test script to changes done in below commits 

https://github.com/g8os/resourcepool/commit/b557da06131c55aa11f172e5bafa1525f7539b35
https://github.com/g8os/resourcepool/commit/caf87165653d40ad822003f2fa826f8d212ea59e

**Comment by khaledkbadr** [comment]
Fixed in commit: https://github.com/g8os/resourcepool/commit/fe47d4e0dc36032a0b06a132189e0e922af80ae1

**Comment by Dinaamagdy** [comment]
## SV
691e5e8d9bcac157d47dca636bac177527e034b4
