### ISSUE TITLE
tmp vdisks

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#269]
Tmp vdisks are implemented as cache disks of which the contents gets cleared in their storagecluster after they get unmounted (vm is stopped).

When implementing tmp disks we also need to harden the vdisk creation api as specified in https://rawgit.com/g8os/resourcepool/tmp-vdisk/raml/api.html#vdisks_post

**Comment by Dinaamagdy** [comment]
Tmp Vdisk service still exist after delete vm 

## SV 
691e5e8d9bcac157d47dca636bac177527e034b4

**Comment by khaledkbadr** [comment]
Current Implementation only removes the data in the `tmp` vdisk not the vdisk service itself. So it still can be found when listing of vdisks.

**Comment by Dinaamagdy** [comment]
Can't verify due to :
https://github.com/zero-os/0-orchestrator/issues/128

**Comment by Dinaamagdy** [comment]
## Software Version 
branch : 1.1.0-alpha-3
commit : 13dd795f563f6ec3db5cc649e0a2272dae26a9bd
