### ISSUE TITLE
Still can list a node (in running state) athough it already has been removed from packet

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#271]
g8os-res is removed from packet and still can be listed as a running machine even though it has been removed 5 mins ago
![ijasd](https://cloud.githubusercontent.com/assets/15011431/26400729/c0a25d20-4082-11e7-81af-bf1d549ad6ce.png)

## version
rp-v: e1bb4cbe0cf7014f9606efac58d12331fa635694

**Comment by grimpy** [comment]
NOrmally monitor should change the state to halted after 30min

**Comment by Dinaamagdy** [comment]
the Issue still exit 
the first node removed from 17 mins and still status running as shown : 
![selection_381](https://cloud.githubusercontent.com/assets/24386802/26675779/74231298-46c5-11e7-80f3-1775d4ba4d11.png)
ae80985db3de3b9a2a77fc1f18ad889d71ef21ee

**Comment by Dinaamagdy** [comment]
need to update pyclient 
## SV
ae80985db3de3b9a2a77fc1f18ad889d71ef21ee
