### ISSUE TITLE
Create bridge with string name start with number fail 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#314]
## Issue
- create bridge with name start with number as shown ,fail with weird error message 
![selection_376](https://cloud.githubusercontent.com/assets/24386802/26589540/96b8b39e-4558-11e7-9684-5afd2e2298f0.png)

**Comment by serboctor** [comment]
The name now accepts values starting with one. Validation was added to make sure it is not longer than 15 characters and is not equal to "default".

**Comment by Dinaamagdy** [comment]
## Software Version 
5e2a9594e0843cea4cbcbe1355e48f42bf5db0a7
