### ISSUE TITLE
Create bridge with invalid cidr in static network mode return 500 instead of 400

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#321]
## Issue
Create bridge with empty setting with static network mode, or same cidr as another bridge return internal server error 500 instead of 400 bad request as shown : 
![selection_378](https://cloud.githubusercontent.com/assets/24386802/26631219/568465ae-460a-11e7-9b88-bfa67b417f55.png)
![selection_377](https://cloud.githubusercontent.com/assets/24386802/26631224/58f58eb2-460a-11e7-86e4-49bfa7db922e.png)

**Comment by Dinaamagdy** [comment]
same with dnsmasq network mode

**Comment by serboctor** [comment]
If the cidr overlaps, we'll return 409. I updated the raml specs.

**Comment by Dinaamagdy** [comment]
## Software Version 
2bd42f38853905db4fffc698dd7fa132e3a9b5fc
