### ISSUE TITLE
Add shorthand endpoints for updating httpproxies in gw api

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#335]
add

* Get /nodes/<nodeid>/gws/<gwname/httpproxes 
* POST /nodes/<nodeid>/gws/<gwname/httpproxes/<host>
* Delete /nodes/<nodeid>/gws/<gwname/httpproxes/<host>

**Comment by khaledkbadr** [comment]
Done in https://github.com/zero-os/0-orchestrator/commit/217405a0b5627d7e72760563d21a97ce4bc9893e

**Comment by Dinaamagdy** [comment]
Version: master @Revision: ffc0bd9e1e6da2e5c44fb126fcdeb5575eb8f169
