### ISSUE TITLE
Add zerotiernodeid property to gateway and container

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#340]
Otherwise there is no way to identify the gateway node in the zerotier network.

**Comment by grimpy** [comment]
This should also and first be done on container, once done on container we can easily copy it from the container service to the gw service

**Comment by serboctor** [comment]
The zerotiernodeid holds the value of containerclient.zerotier.info()['address'] which only works if the container has a nic of type 'zerotier'.

**Comment by ahmedelsayed-93** [comment]
### software versions
orchestrator : bb0fb08
