### ISSUE TITLE
The default status of the new GW is halted instead of running 

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#353]
**Description**
The default status of the new GW is halted however, the expected result should be running 

**Steps**
Create a new GW using the basic parameters
List the containers and check the GW status 

**Actual result**
Halted

**Expected result**
It should be running

**SW versions**
master

**Comment by Dinaamagdy** [comment]
## SV
b1e44aedf4b81233242be700ed08ec6b129a89f0
