### ISSUE TITLE
Create GWs with the same name will return wrong status code

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#358]
**Description**
Create GWs with the same names will return 201 status code

**Steps**
- Create GW_1
- Try to create another GW with the same name

**Actual Result**
- The request status code is 201

**Expected result**
- Request status code should be 409 with error message

**Comment by Dinaamagdy** [comment]
## SV
f74e7be69b8594dba2a6b4d7c15933f25c3919b0
