### ISSUE TITLE
installgrid script: CODEDIR varialbe is not defined 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#366]
https://github.com/zero-os/0-orchestrator/blob/master/scripts/installgrid.sh#L41

![image](https://cloud.githubusercontent.com/assets/24386820/26783310/c59d5fd6-49f7-11e7-82a9-26d6ba134b10.png)

**Comment by Dinaamagdy** [comment]
## Software Version 
af5cc20dffa47b6cbd695a8c680c9ca856e3fc90
