### ISSUE TITLE
install-orchestrator script should wait until user authorize js9 docker as a zerotier member instead of exit with error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#375]
install-orchestrator should wait until user authorize js9 docker as a zerotier member instead of exit with error

**Comment by maxux** [comment]
Please try the install from `master-orchestrator-ztinstall` branch to confirm it fix the issue

**Comment by ahmedelsayed-93** [comment]
### version
orchestrator: 6b78e46
