### ISSUE TITLE
Creating a GW with only one nw interface produces 500

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#376]
We have to create a GW with at least two nw interface, but if we send a request with only one interface, it will produce an internal server error.
![image](https://cloud.githubusercontent.com/assets/17981089/26820746/36e4e9d2-4aa4-11e7-9403-37684ec0a843.png)

**Expected result**
Bad request

**Comment by zaibon** [comment]
should be fixed with https://github.com/Jumpscale/ays9/issues/14

**Comment by islamTaha12** [comment]
@zaibon 
This pull fix a half of problem. It fix the issue from AYS but we have to fix it in orchestrator too

This pr changed the body but the status code still 500
![image](https://cloud.githubusercontent.com/assets/17981089/26826037/bb11eb5c-4ab7-11e7-8b1d-26e0b72b6f8d.png)

**Comment by islamTaha12** [comment]
@abdulrahmantkhalifa which version should we use to verify

**Comment by Dinaamagdy** [comment]
## Software Version 
e61e9e1b8cf7753cc7f3f73b5f3a4dffc7cdc066
