### ISSUE TITLE
Document different types of backplane networks

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#382]
We have two types:
- g8 setup with nodes interconnected via a 10GE+ network
- packet.net setup

Document how they need to be configured using their respective blueprints.

Add a reference to this new documentation from the setup docs: https://github.com/zero-os/0-orchestrator/blob/master/docs/setup/setup.md as the step to take after installing the orchestrator server.

**Comment by FastGeert** [comment]
See setup documentation

**Comment by Dinaamagdy** [comment]
## Software version 
053e9c8320ef9e13b668bd679e8c5b8829bcca3e
