### ISSUE TITLE
Document how to configure the configuration blueprint

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#383]
After installing the orchestration server the first step to take is to issue the configuration blueprint containing the correct versions fo jumpscale, flists, zero-os nodes

**Comment by serboctor** [comment]
@FastGeert it is already documented here https://github.com/zero-os/0-orchestrator/blob/master/docs/versioning.md

**Comment by serboctor** [comment]
Extended this document too https://github.com/zero-os/0-orchestrator/blob/master/docs/setup/setup.md

**Comment by Dinaamagdy** [comment]
## SV
053e9c8320ef9e13b668bd679e8c5b8829bcca3e
