### ISSUE TITLE
Delete GW API can't delete bad configured gateways

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#390]
**Steps**
- Send a creation GW request to create GW_16 without setting "gateway" parameter in the config.
- Response: Bad request
- List the containers, u will find the GW_16 container with status halted
- Try to delete it using the GW delete api

**Actual Result**
![image](https://cloud.githubusercontent.com/assets/17981089/26827072/d69f6a3a-4abb-11e7-8746-4de4c723e61a.png)

**Software Vesrsion**
Master

**Comment by grimpy** [comment]
Your screenshot is showing delete of GW_16, your ticket talks about GW_10? Should I trust this ticket?

**Comment by islamTaha12** [comment]
@grimpy U can trust it nw

**Comment by grimpy** [comment]
Can't reproduce this, create of invalid config does not create a halted gw for me, please provide payload.

**Comment by islamTaha12** [comment]
I updated my ays and nw it doesn't create a container if the request raises an error. but before the update I had created many halted GW

![image](https://cloud.githubusercontent.com/assets/17981089/26830831/6c83f0bc-4aca-11e7-8fae-176b5e56219d.png)

![image](https://cloud.githubusercontent.com/assets/17981089/26830897/ba40d356-4aca-11e7-9fc3-fa83f3f638f1.png)

**Comment by FastGeert** [comment]
If you can't get into this situation anymore, then the problem is that here is no more problem
