### ISSUE TITLE
Can't use sudo in boot disk  in vm 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#420]
## Steps
- create vm with vdisk with template "ardb://hub.gig.tech:16379/template:ubuntu-1604 "
-  connect to it 
- try to use sudo in root directory 

## Issue
![selection_402](https://user-images.githubusercontent.com/24386802/26876526-e80c98d0-4b86-11e7-9c93-199bc5348177.png)

**Comment by FastGeert** [comment]
@Dinaamagdy You show errors in the filesystem / storage.

What was your setup, could this reveal a bug in the NBD server

**Comment by Dinaamagdy** [comment]
1-I created vdisk  with "ardb://hub.gig.tech:16379/template:ubuntu-1604"   template  
2- create vm with this vdisk
3- stop machine and start it again ,this error happen when I login to vm again .

**Comment by zaibon** [comment]
@Dinaamagdy can you give us the detail about which version you're running ect ?

**Comment by Dinaamagdy** [comment]
can't reproduce it again in current version 2e6d4bc0c35e1469b9f579e38b09b178396078ae
