### ISSUE TITLE
Auto disk wiper

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#433]
We need an enhancement to auto wipe disks from the bootstrap service because the current manual procedure wil not work anymore when the zero-os nodes only listen on zerotier network.

So add a switch to the bootstrap service `wipeDisks`. If the swicth is enabled the bootstrap service will wipe all disks of an unknown zero-os node before configuring the fuse cache.

**Comment by ahmedelsayed-93** [comment]
### software version 
orchestrator: 05bcdb04b
