### ISSUE TITLE
Rename rocksdb-version parameter to storage-engine-version

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#457]
To specify the ardb flist version we are now using `rocksdb-version`, which is a bad name because it points to the storage engine used by ardb to store the key values, while it is actually a pointer to the flist we need to start for bringing up the key value stores.

`storage-engine-version` is a better name because it points more to what the flist actually delivers.

> **Important** Also adapt the documentation (setup.md)

**Comment by grimpy** [comment]
This only makes sense if renaming the service itself aswell.

**Comment by Dinaamagdy** [comment]
## Software Version 
d7c691a81bcd6166e5a5046b7b3c5a1f942be39b
