### ISSUE TITLE
GetContainerCPUInfo GetContainerMemoryInfo are not implemented

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#468]
Implement the above methods

**Comment by Dinaamagdy** [comment]
I can't use  /nodes/{nodeid}/containers/{containername}/mem Api 

![image](https://user-images.githubusercontent.com/24386802/27281202-265750e0-54eb-11e7-82c9-79f3ee5d3304.png)

## Software version
61b3cad75e1fe00ca11aae979d4b3753e27cebee

**Comment by zaibon** [comment]
This kind of output makes me think the orchestrator is not running at all. can you please make sure you setup is correct.

**Comment by Dinaamagdy** [comment]
no orchestrator is running as I can get container as shown 
![selection_423](https://user-images.githubusercontent.com/24386802/27283473-c73117ae-54f4-11e7-9b2a-9a75842f28e7.png)
but when I try get mem info give me this output and orchestrator still working :
![selection_422](https://user-images.githubusercontent.com/24386802/27283515-f65b18e0-54f4-11e7-9c62-1cc365e8685f.png)

**Comment by serboctor** [comment]
All directAccess apis were broken. Please try again.

**Comment by Dinaamagdy** [comment]
## Software version 
0d6e8fdd6f4d87c6890f51c0340da20316709411
