### ISSUE TITLE
Revised storage setup

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#471]
For redudancy reasons we need to setup storage as follows:
![architecture](https://user-images.githubusercontent.com/15246294/27177335-4edec4a8-51c6-11e7-804a-e848176c972f.png)

So both the primary and backup storage cluster need to be setup with a metadata ardb server. Also the tlog server needs to be deployed on another machine if possible.

@robvanmieghem can you point the guys to the docs in 0-disk on how to configure the tlogserver process for the backup storage cluster connection.

Please use the storage-setup branch

**Comment by robvanmieghem** [comment]
https://github.com/zero-os/0-Disk/blob/master/docs/tlog/config.md

**Comment by Dinaamagdy** [comment]
can't validate due to :
https://github.com/zero-os/0-orchestrator/issues/662

**Comment by Dinaamagdy** [comment]
## Software Version 
2b48d48e8d08470aaf9e8c2217ec60eff4122358
