### ISSUE TITLE
VM shutdown doesn't clean the zerodisk services

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#473]
VM shutdown does not stop nbd/tlog servers, hence makes it impossible to do disk operation like disk rollback

**Comment by FastGeert** [comment]
@khaledkbadr what do you mean with clean?

**Comment by khaledkbadr** [comment]
@FastGeert I updated the description

**Comment by grimpy** [comment]
https://github.com/zero-os/0-orchestrator/pull/475 should fix this

**Comment by Dinaamagdy** [comment]
## Software Version
61b3cad75e1fe00ca11aae979d4b3753e27cebee
