### ISSUE TITLE
Deploying multiple storage clusters causes disks and ports acquiring clash

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#501]
Currently `strage_cluster` service check for open ports and free disks in the `init` stage and acquire free ports and disks needed. However when deploying multiple storage clusters, the services checks for the free resources but they get the same resources as free which causes all kinds of problems at the `install` stage.

**Comment by FastGeert** [comment]
Just block the creation of multiple storage clusters at the same time.

**Comment by ahmedelsayed-93** [comment]
### software version
master : 2e6d4bc0c
