### ISSUE TITLE
zerotier_apis: get zerotier info returns old data

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#510]
API ```GET /nodes/{nodeid}/zerotiers/{zerotierid}```

### scenario
- join **Private** zerotier network
- authorize the node from zerotier website 
- get zerotier network info
 ### result
the status still **ACCESS_DENIED** instead of **OK**
and the **assignedAddresses** was empty 

![image](https://user-images.githubusercontent.com/24386820/27334101-77fd3242-55c8-11e7-8261-f76d2d54e3be.png)

**Comment by FastGeert** [comment]
Add a monitoring action

**Comment by serboctor** [comment]
Monitoring added with a 5 minute interval.

**Comment by Dinaamagdy** [comment]
## Software version 
92d0ba099d207cea3c53c7010b49b9c1459a6631
