### ISSUE TITLE
 install-orchestrator script: No JWT token error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#523]
### executed command
```
bash install-orchestrator.sh master 17d709436c86f100 SHFsehFPCBGC6KVja1nHMaAw64QgQFgg testorch
```
### #after installation 
ays return ```No JWT token``` error
and didn't authorize any node

![image](https://user-images.githubusercontent.com/24386820/27393450-a38d0e32-56a9-11e7-9243-530f5018c6b8.png)

### software version
orchestrator : master : 783b8552

**Comment by FastGeert** [comment]
Did you boot your nodes correctly?

**Comment by ahmedelsayed-93** [comment]
the ipxe url was 
https://bootstrap.gig.tech/ipxe/zero-os-master/17d709436c86f100/orgnization=testorch, the node joined the zerotier network but ays didn't try to authorize

**Comment by zaibon** [comment]
should be fixed by : https://github.com/zero-os/0-orchestrator/commit/a1091107ee87d8831e5f1a3fab024a904b2d23db
passing it to verification

**Comment by ahmedelsayed-93** [comment]
### software versions
master : 92d0ba0
