### ISSUE TITLE
Install script should only check validity of the given zerotier network

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#546]
In this line in the install script : https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh#L82

We should also grep on the zerotier network id. Cause the docker could also have some other network but that should not impact on the install of the orchetrator

**Comment by ahmedelsayed-93** [comment]
same issue still exists

### software version
master : ebd22d1

check this line https://github.com/zero-os/0-orchestrator/pull/575/files#diff-64269b2bb3e199017b7030e170ca9668R87

**Comment by ahmedelsayed-93** [comment]
software version
master : 8fc8b94
