### ISSUE TITLE
Healthcheck API

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#561]
The 0-orchestrator needs to be able to expose how good (or how bad) things are going on.

For this we need a health API that can report in one call how good it is doing.

### List node health status
```http
GET /health/nodes HTTP/1.1

200 OK

[
   {
        "nodeid": "6758765875",
        "name": "cpu-05",
        "healtcheckid": "594b2664-ff67-41b6-bafc-e4f4683a1973", # used to link to knowledge base

        "status": "ERROR" // status can be ["OK", "ERROR"]
    }
]
```

### List all health checks of a node
```http
GET /health/nodes/{nodeid} HTTP/1.1

200 OK

[
   {
        "id": "node_6758765875_disk_sdb",
        "name": "Disk check",
        "resource": "/nodes/6758765875/disks/sdb",
        "status": "FAIL",
        "message": "Cannot mount disk"
    }
]
```

### Storagecluster & Vdisks
Implement a similar health api for these resources like for nodes.

**Comment by grimpy** [comment]
Most healtchecks will be implemented by means of a python3 cli script.
Those cli scripts will be spawned in js9 container on top of the host.

The cli scripts output the healthcheck data info

```
{
        "id": "node_6758765875_disk_sdb",
        "healtcheckid": "594b2664-ff67-41b6-bafc-e4f4683a1973", # used to link to knowledge base
        "name": "Disk check",
        "resource": "/nodes/6758765875/disks/sdb",
        "status": "FAIL",
        "message": "Cannot mount disk"
    }
```

**Comment by despiegk** [comment]
- how do we know what to run where (on which host)?
- if we do it this way its for sure a non long term solution because this breaks our security approach of zero-OS.
- long term best would be to have certain of these checks implemented on zero-os golang level & behind redis api.
- if we win time to do it like this, ok for me

**Comment by Dinaamagdy** [comment]
## Software Version 
aeaba8ae2784c24d504ea65ab93569947523bd5b
