### ISSUE TITLE
Add api to get dump of statistics

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#566]
Add API
```
GET /nodes/<nodeid>/stats

{"statkey1": statobj1, "statkey2": statobj2}
````

Get all statskeys from the redis of the node

**Comment by despiegk** [comment]
- shouldn't this be latest, 5min & hourly?
- we should be able to get all info from aggregated redis

**Comment by grimpy** [comment]
@despiegk you are right the title was misleading the idea of this api was to get the stats keys in out in its raw mode. The time frame if in the key itself.

**Comment by Dinaamagdy** [comment]
can't validate due to

**Comment by ahmedelsayed-93** [comment]
### software versions
master : 0675fcc
