### ISSUE TITLE
Implement influxdb service

### ISSUE THREAD

**Issue by serboctor** [zero-os/0-orchestrator#578]
Add a service influxdb to start influxdb on a node.

**Comment by serboctor** [comment]
Example of a blueprint to create influxdb service:
`influxdb__one:
  node: '525400123456'
  port: 8086
  databases:
  - 'one'
  - 'two'

actions:
  - action: install
`

**Comment by Dinaamagdy** [comment]
## Software Version 
92d0ba099d207cea3c53c7010b49b9c1459a6631
