### ISSUE TITLE
Monitor ARDB server process health

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#580]
Currently we only check if the process is running. Thats not good enough. We also need to investigate the healthyness of the process.

So we need to execute the following to validate if the ARDB is still healthy:
```
127.0.0.1:16379> SET testkey geertwashere
OK
127.0.0.1:16379> GET testkey
"geertwashere"
127.0.0.1:16379> DEL testkey
(integer) 1
127.0.0.1:16379> EXISTS testkey
(integer) 0
```

**Comment by khaledkbadr** [comment]
To implement ardb healthcheck we need `nbdserver` to add support for retrying to connect to the ardb server which is not implemented yet so this issue is blocked until such support exist

**Comment by grimpy** [comment]
We need to change ardb to listen on the storage network and the management network, then we can in the monitor (recuring task) of the ardb service implement this check which can change the status of the service

**Comment by Dinaamagdy** [comment]
can't validate
