### ISSUE TITLE
Add watchdog for gateway services

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#582]
Use watchdag to monitor and restart caddy/cloud-init and dnsmasq of the gateway

**Comment by Dinaamagdy** [comment]
it sometimes works, and sometimes not , may it relate to https://github.com/zero-os/0-orchestrator/issues/666

**Comment by Dinaamagdy** [comment]
still same not always work

**Comment by Dinaamagdy** [comment]
it still not  stable 
## Software Version 
5cfc4d99b8c58fce0596a1e9551e1a2fefcac1d7

**Comment by Dinaamagdy** [comment]
## Software Version 
012719ca7375c9a5ba500bc403a61a15b0873b53
