### ISSUE TITLE
Monitor VM

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#591]
- Monitor VM qemu process with 0-Watchdog

**Comment by serboctor** [comment]
Added a watchdog handler for the "kvm.events" messages. 
If a vm was killed using "kill -9 <process_id>", it starts the vm again. If it was killed using "kill <process id>" it makes sure the vm service is up to date.

**Comment by Dinaamagdy** [comment]
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091
