### ISSUE TITLE
Healthcheck: InfluxDB monitor

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#596]
Implement in influxdb service monitor action.

Checks status of InfluxDB databases. If not running an error condition is thrown.
Result will be shown in the "Databases" section of the Grid Portal / Status Overview / Node Status page.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/db_check.py

**Comment by mie00** [comment]
Blocked on #864

**Comment by grimpy** [comment]
As discussed in the master scrum we will close this issue as this is part of a bigger story.
