### ISSUE TITLE
Healthcheck: Deployment test

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#597]
Implement in delpoyment_test service monitor action.

Tests every predefined period (default 30 minutes) whether test VM exists and if exists it tests write speed. Every 24hrs, test VM is recreated.
Result will be shown in the "Deployment Test" section of the Grid Portal / Status Overview / Node Status page.
Generates warning if write speed is lower than 50 MiB / second.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/deployment_test.py

**Comment by abdulrahmantkhalifa** [comment]
what image should be used to create the test vm ?

**Comment by FastGeert** [comment]
Do not like this. Also in russia we don't use it anymore
