### ISSUE TITLE
Healthcheck: Disk usage

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#599]
Implement in node service monitor action

Checks status of all physical disks and partitions on all nodes, reporting back the free disk space on mount points.

Throws WARNING per mount point if >90% used, throws ERROR per mount point if >95% used.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/disk_usage_check.py

**Comment by ahmedelsayed-93** [comment]
### software versions
master : 4b849b3ef
