### ISSUE TITLE
Healthcheck: Network load

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#601]
Implement in node service monitor action

Check the bandwith consumption of the network

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/network_load.py

**Comment by ahmedelsayed-93** [comment]
### software version
master : 4768508

**Comment by ahmedelsayed-93** [comment]
### Scenario 
- remove node form zerotier.
- wait until the status of the node be halted
- get node healthcheck

![image](https://user-images.githubusercontent.com/24386820/28914973-d8aa28c4-783d-11e7-9b02-d8ca32a9eb7c.png)

### software version
master : 13e218d5c

**Comment by ahmedelsayed-93** [comment]
### software version
master : 2043f538
