### ISSUE TITLE
Healthcheck: Network bond

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#602]
Implement in node service monitor action

Monitors if a network bond (if there is one) has both (or more) interfaces properly active.
Problems are reported in the "Hardware" section of the Grid Portal / Status Overview / Node Status page.

https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/networkbond_check.py

**Comment by Dinaamagdy** [comment]
## Software Version 
012719ca7375c9a5ba500bc403a61a15b0873b53
