### ISSUE TITLE
Healthcheck: Network stability 

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#603]
Implement in node service monitor action

Tests network between nodes
Make sure all types of network can reach eachother
Ping nodes for 10 times
When less then 90% produce a warning
When less then 70% procede an error
When timings are more then 10ms produce a warning
When timings are more then 200ms produce am error
Futhermore it makes sure that all nics in network have same MTU
Otherwise produces an error message

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/networkstability.py

**Comment by ahmedelsayed-93** [comment]
### software version
master : 4768508
