### ISSUE TITLE
Healthcheck: Open file descriptors

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#604]
Implement in node service monitor action

Checks the number of open file descriptors for each process.
Result will be shown in the "System Load" section of the Grid Portal / Status Overview / Node Status page.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/openfd_check.py

**Comment by despiegk** [comment]
is the monitoring call in golang? (core of zero-os?)

**Comment by despiegk** [comment]
think is not right implementation, need to see the zero-os specs for stdout/err redirection

**Comment by ahmedelsayed-93** [comment]
message id is always equal to -1

![image](https://user-images.githubusercontent.com/24386820/28826685-41c5e984-76cb-11e7-833a-36ff174a1a6a.png)

### software version
master : 91f54c95

**Comment by serboctor** [comment]
The id is always going to be -1 if everything is ok. If a process exceeds ofd, the id will be the process number.

**Comment by Dinaamagdy** [comment]
## Software version 
3784e265fb38bef07fd616b8d34aae2d7fc01b43
