### ISSUE TITLE
Healthcheck: QEMU

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#606]
Implement in vm service monitor action

Inspects the qemu log files of running VMs and reports if there was any errors.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/qemulogs_check.py

**Comment by abdulrahmantkhalifa** [comment]
- logs are parsed from  /var/log/libvirt/qemu/<vmname>.log , to check for the word error 
- line with error will be added to healthcheck vailable at 
- http://{{url}}:{{port}}/health/nodes/{{ nodeid }} under vm-logs part

**Comment by ahmedelsayed-93** [comment]
i tried 4 scenarios to corrupt the vms:
- kill qemu proccess
- kill nbdserver
- remove vm server.socket file
- put "error" word in ```/var/log/libvirt/qemu/{{vmname}}.log``` file

and after each case the health check was ok 
 
![image](https://user-images.githubusercontent.com/24386820/29416416-465f33fe-8366-11e7-9398-4d86c1d6781d.png)


### software versions
master : 96700d6f

**Comment by Dinaamagdy** [comment]
## Steps
- Create etcd cluster and storage in node 1 
- Create vm in node 2 
- kill node 1
## Issue 
check qemu health check  still ok 
## Software Version 
0d238efa01e6f8ee291f2d3cec4d1e918aa39212

**Comment by abdulrahmantkhalifa** [comment]
## for Testing
- create a node with storagecluster and etcd 
- create another node with vm and disk on sed storage cluster 
- login to vm 
- force close node with storage cluster 
- try read/write operation such as touch file 
- check logs in http://{{url}}:{{port}}/health/nodes/{{ nodeid }} under vm-logs part

**Comment by Dinaamagdy** [comment]
## Software Version 
337169e32a2e4d28fb06178c06c6d93d2e4c47c0
