### ISSUE TITLE
Healthcheck: Stack status

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#607]
Implement in node service monitor action

Checks the status of each stack (CPU node).
ERROR state is automatically attributed to a stack by OpenvCloud - this is done if a specific action cannot be executed anymore on the CPU Node.
Result will be shown in the "Stack Status" section of the Grid Portal / Status Overview / Node Status page.

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/stackstatus.py

**Comment by grimpy** [comment]
I dont think this is still relevant, node monitor updates it local status.

**Comment by Dinaamagdy** [comment]
status and text should be replaced 
```	
	{
			"id": "nodestatus",
			"name": "Node Status",
			"resource": "/nodes/248a07e77340",
			"messages": [
				{
					"id": "node",
					"status": "Node is running",
					"text": "OK"
				}
			],
			"category": "Node Status",
			"lasttime": 1501684900,
			"interval": 30,
			"stacktrace": ""
		}
```
## Software version
3784e265fb38bef07fd616b8d34aae2d7fc01b43

**Comment by Dinaamagdy** [comment]
#Software Version
13e218d5cf8395ebb378ac9adb15afd6972df668
