### ISSUE TITLE
Healthcheck: Network performance

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#608]
Implement in node service monitor action

Tests bandwidth between nodes and itself
Generates a warning if bandwidth is below 50% of the maximum speed
Generates an error if bandwidth is below 10% of the maximum speed

See https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/networkperformance.py

**Comment by grimpy** [comment]
This was always disabled cause it caused more trouble then it ever solved. I don't recommend reimplementing this. @FastGeert @delandtj
