### ISSUE TITLE
Healthcheck: Node temperature

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#609]
Implement in node service monitor action

Checks the CPU + disk temperature of the system.
Result will be shown in the "Temperature" section of the Grid Portal / Status Overview / Node Status page.

See for reference https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/fan_check.py

**Comment by ahmedelsayed-93** [comment]
### software version
 master 0675fcc
