### ISSUE TITLE
error when running install-orchestrator script

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#610]
error
![image](https://user-images.githubusercontent.com/24386820/27820542-59c26cb6-609f-11e7-960e-5dedf97c9523.png)

log file
![image](https://user-images.githubusercontent.com/24386820/27820473-0c899758-609f-11e7-8a6c-f41f252739d3.png)

**Comment by FastGeert** [comment]
Need more logging in the logfile. No clue what went wrong

**Comment by zaibon** [comment]
@ahmedelsayed-93 
can you validate this is still the case, I think this bug has been fixed in the mean time.
