### ISSUE TITLE
Create selfhealingscript to cleanup ssh daemons created by migrations

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#618]
Check if there are still ssh daemons running on the node which are left over from vm migrations

**Comment by despiegk** [comment]
lets discuss how this will be implemented

**Comment by abdulrahmantkhalifa** [comment]
things that will be cleaned up 
 - ssh.config files that realate to **finished** or **errored** migrations located in /tmp 
 - sshd processes that relates to **finished** or **errored** migrations 
 - tcp services with insance name tcp_node_port that realtes to **finished** or **errored** migrations
 - opened ports for  **finshed** or **errored** migration

**Comment by Dinaamagdy** [comment]
tcp service still exist after migration end 
```
---------------------------------------------------                     [26/768]
Service: tcp_248a07e76f80_4000 - Role: tcp
state : ok
key : f56191e751004185b0e64eb56f8e57be

Instance data:
- node : 248a07e76f80
- port : 4000

Parent:
node!248a07e76f80

Children: None

Producers:
node!248a07e76f80

Consumers: None

Recurring actions: None

Event filters: None
```
## Software Version
5cfc4d99b8c58fce0596a1e9551e1a2fefcac1d7

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce

**Comment by ahmedelsayed-93** [comment]
ssh.config still exists on the new node after migrating 

![image](https://user-images.githubusercontent.com/24386820/29418730-70a988d8-836d-11e7-8275-f11b08e7a631.png)

### software versions
master : 96700d6

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce

**Comment by Dinaamagdy** [comment]
still sshd in new node exist 
as shown 
```
STATE: 0 SUCCESS
STDOUT:
 1222 root       0:00 /usr/sbin/sshd -e -D
 7091 root       0:00 /usr/sbin/sshd -f /tmp/ssh.config_vm6_4000
 7201 root       0:00 /usr/sbin/sshd -f /tmp/ssh.config_vm6_4001
21659 root       0:00 /bin/sh -c ps -a |grep sshd
21662 root       0:00 grep sshd

STDERR:

DATA:
```
## Software Version 
e7383bcca187748a6ac6f7e54feb4fa5433e843b

**Comment by Dinaamagdy** [comment]
## Software Version 
5d71c78faa37c0316e4d5f2143e9e6096d8f7fa9
