### ISSUE TITLE
Selfhealing: 0-ORK

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#620]
# Problem
It is not possible to remotely monitor nodes to prevent them from being DDOS'ed, just because when it really happens you can't access them anymore.

# Solution
We will need to run a daemon on each node (can do it in a privileged container) that can execute the self-healing actions locally, and then report to AYS via the pub sub logging infrastructure that it has executed a self healing action eg by disabling a network interface. AYS can then investigate to which vm / container this interface belongs, and subsequently set the vm / container in the "network_killed" status and report via the health-checks what happened. The user can then over the console / core-x api fix the problem, and resume the networking of the vm / container.

# Deliverable
- 0-ORK daemon written in GO, that monitors packets in VxLan interfaces, vm interfaces and GW pub ip interfaces and communicates via the pub sub logging infrastructure if an action was taken, or to notify a warning status.
  - over 8k packets/second ==> HEALTHCHECK WARNING and add 200ms latency to the NIC
  - over 10k packets/second ==> HEALTHCHECK ERROR & SELFHEALING action; i.e. shut the NIC down
- flist for 0-ORK container (https://github.com/zero-os/0-core/issues/396)
- core-0 will spawn the 0-ORK container at boot automatically (See zero-os/0-core#396 for detail)
- "network_killed" status on vm / container
- health-check report towards outside world
- documentation on the whole system

See also:
* https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/healthchecks/vm_network_load.py
* https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/maintenance/selfhealing_threashold.py

**Comment by despiegk** [comment]
can this be done as co-routine in main daemon or is this dangerous?

**Comment by despiegk** [comment]
Kristof De Spiegeleer, [07.07.17 02:02]
I believe we should never rely on privileged containers to do anything because this breaks the security concept of zero-os

Kristof De Spiegeleer, [07.07.17 02:02]
the goal is that golang is the master process controlling everything

Kristof De Spiegeleer, [07.07.17 02:03]
from moment you allow privileged containers you break security completely (hacker surface expands x 100000000000)

Kristof De Spiegeleer, [07.07.17 02:03]
if we need to do this short term to win some development time, fine by me but for sure not long term

Kristof De Spiegeleer, [07.07.17 02:06]
if we need to run subprocess, we need to make this subprocess part of the building process of our zero-os

Kristof De Spiegeleer, [07.07.17 02:06]
and no-one should be able to remotely spawn privileged container

Kristof De Spiegeleer, [07.07.17 02:06]
it is prob ok that zero-os himself spawns a privileged container to get a predefined flist as a primitive function insize zero-os

Kristof De Spiegeleer, [07.07.17 02:07]
so not generic container driven by ays

**Comment by FastGeert** [comment]
I think that the zero-os API should allow the creation of privileged containers, but via the 0-orchestrator API we should not allow it.

Currently we use privileged containers for running 
- OpenvSwitch (creates devices, needs to be privileged)
- NBD & Tlog server (currently runs privileged but host networking should be enough)

Eg for OpenvSwitch we cannot go around running privileged containers.

See also https://github.com/zero-os/0-orchestrator/issues/674

**Comment by FastGeert** [comment]
@despiegk 

> can this be done as co-routine in main daemon or is this dangerous?

The advantage of running it as a separate privileged container is that is more easily to maintain, update, without needing core-0 to be rebooted.

**Comment by FastGeert** [comment]
@despiegk we changed the specs according to your recommendations

**Comment by muhamadazmy** [comment]
@FastGeert I assume this is to be added to the current logic of 0-ORK (killing processes/VMs if the cpu usage and/or memory exceeds certain thresholds).

While privileged containers can access system resources, they still run in a separate PID namespace, hence they can not know about processing running on the node or on other containers.

We have 2 options:
- Add more options to container creations to refine what namespaces it should use.
- Run ORK directly on the node (easier of course) but we will need to include it in the image.

**Comment by zaibon** [comment]
I would prefer we do the second option. 
I don't think we should allow container to be more privileged.

**Comment by zaibon** [comment]
See https://github.com/zero-os/0-core/issues/396 for detail about how we are going to spawn/run the 0-ork

**Comment by serboctor** [comment]
Note to QA: This needs to be tested in a production environment.

**Comment by serboctor** [comment]
After some discussions with @grimpy  and @muhamadazmy  we agreed that the status update should be on the nic, not on the container/vm since they may have other reachable nics. I created this ticket for that change https://github.com/zero-os/0-orchestrator/issues/986.

**Comment by Dinaamagdy** [comment]
test in be-scale-2 with steps 
- create container C1  in node1 with vxlan network 
- create container C2 in node2 with same network  for C1
- try to make C1 ping C2 ,but failed to connect to each other due to hardware issue in env 

#### So this Issue blocked till env be available

**Comment by Dinaamagdy** [comment]
## Software Version 
a7ed0d5e0925d86bb95c95726eff3635efca7440
