### ISSUE TITLE
Selfhealing: rotate log files

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#622]
Implement in node service monitor action

Find all logs known logs files and log rotate them via logrotate command if total amount of logs exceed 1GB

See 
https://github.com/0-complexity/selfhealing/blob/master/jumpscripts/maintenance/logs_truncate.py

**Comment by ashraffouda** [comment]
logrotate is not installed on the system, we have a method that do the log rotate in core0 client 
`client.logger.reopen() ` this method do rotation for core.log in /var/log 
can we use it instead of `logrotate` ?
and are there any files else that need to do the rotation for it ?

**Comment by ahmedelsayed-93** [comment]
messages id always equal to -1

![image](https://user-images.githubusercontent.com/24386820/28786143-9b049d6e-7618-11e7-915a-38183485b150.png)

### software version
master : 4768508

**Comment by Dinaamagdy** [comment]
## Software Version 
4685811aa99ceffb2d56949664d5d728a0d938b1
