### ISSUE TITLE
Autodeployment of statsdumper

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-orchestrator#626]
For our stats collector we need an influxdb deployed somewhere on a node. AYS needs to be aware of this influxdb service.

We will create a service which wraps influxdb which has some special logic to make nodes join this influxdb, the name of this service will be statsdb (it will consume a influxdb which it will deploy itself, with a fixed dbname).

When a node is deployed and this statsdb service is found the statscollector will be deployed as part of the node.install.
When a node is deployed and the statsdb does not exist this step is skipped.

To make sure all nodes have statscollector running when a statsdb is deployed, we will install the statscollector on the nodes as part of the statsdb.

**Comment by Dinaamagdy** [comment]
statsdb blueprint results this error : 
```
    raise j.exceptions.RuntimeError("container didn't stopped")
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: container didn't stopped ((type:runtime.error)
[Mon10 10:02] - RunStep.py          :84  :j.atyourservice.server         - INFO     - runstep 5: error
[Mon10 10:02] - Run.py              :108 :j.atyourservice.server         - ERROR    - error during execution 
of step 5 in run 9598d46ffe205a37d3e527857fa61e1a
Error of job: statsdb!two (install):
*TRACEBACK*********************************************************************************
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: container didn't stopped ((type:runtime.error)

```

**Comment by serboctor** [comment]
Added a check on the status of the statscollector before attempting to stop it.

**Comment by Dinaamagdy** [comment]
## Software Version 
f2c4c5ed9fb94a8316f2b118d16d68fd36078777
