### ISSUE TITLE
IYO organizations with spaces result in a failing setup procedure

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#628]
- Surround all arguments in the setup.md with double quotes

Reference:
![image](https://user-images.githubusercontent.com/15246294/27860549-67dcf54e-617d-11e7-9046-9e03f9d9a1e3.png)

**Comment by Dinaamagdy** [comment]
still orchestrator work with name before space only 
## Steps
- use  organization name with space as example "test organization "
- run orchestrator script
```  you will find orcherstrator server work with test only ```

**Comment by Dinaamagdy** [comment]
it works now , but when I generate jwt with this organization  ,and try to use it ,it always gives 403 Forbidden in any request 
 ## Software Version 
8e16c6a1af4aed070acdbf7940c5bc287d742da4

**Comment by Dinaamagdy** [comment]
## Software Version
2ce75f13c3138bbe34c088d95c1be00bbbbfa6c7
