### ISSUE TITLE
Restart node gives an error when deleting container cache

### ISSUE THREAD

**Issue by mie00** [zero-os/0-orchestrator#629]
When a node is restarted, it gives this error.

```
"exited with error (ERROR): [Delete subvolume (no-commit): 
'/mnt/storagepools/525400123456_fscache/filesystems/containercache'\n ERROR: cannot delete 
'/mnt/storagepools/525400123456_fscache/filesystems/containercache': Directory not empty\n]"
)
```

This happens because the containercache subvolume has subvolumes inside, apparently there is no recursive subvolume deletion in btrfs, so it has to be done manually.

This happens inside pyclient/zeroos/orchestrator/sal/Node.py under `_mount_fscache` when deleting the container subvolume.

So a solution for that is to use `btrfs subvolume list {subvolume} -o` to list the children subvolume, sort them and remove them from upside down, just to make sure that they are done in the correct order.

**Comment by ahmedelsayed-93** [comment]
software version

master : 92d0ba0
