### ISSUE TITLE
container_apis: Get non-existing process details returns internal server error

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#638]
### API 
```GET /nodes/{nodeid}/containers/{containername}/processes/{processid}```

![image](https://user-images.githubusercontent.com/24386820/27910505-bed7da20-6255-11e7-8020-d83525aac348.png)

### software version
master : 92d0ba0

**Comment by zaibon** [comment]
It should return a 404.
Also there is a bug in the print of the error message.

**Comment by ahmedelsayed-93** [comment]
issue  still exists
![image](https://user-images.githubusercontent.com/24386820/28022956-d00dc7d4-658c-11e7-88b1-7c4193ad7fcd.png)


### software version
master : ee1db4d

**Comment by Dinaamagdy** [comment]
## Software Version 
9d8b29fe837b0ce88b26c18a8016fb8b3d350dfe
