### ISSUE TITLE
backup/restore of container

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-orchestrator#664]
- use restic as command line to backup/restore a full container
- destination ftp or sftp
- create some api in orchestrator for it with right properties

remarks
- backup of full storage space (no optimizations around flist)
    - restic will do the dedupe & metadata handling
- need to be possible for people to restore to e.g. docker container

**Comment by despiegk** [comment]
remarks
- backup of full storage space (no optimizations around flist)
- need to be possible for people to restore to e.g. docker container

**Comment by zaibon** [comment]
@muhamadazmy can you take care of created the related issue for 0-core and 0-initramfs that are needed to complete this?

**Comment by rkhamis** [comment]
Backup/Restore APIs should be exposed in the orchestrator. As well as Import/Export (Same calls to 0-core)

Should be implemented through AYS
