### ISSUE TITLE
spec error/stdout feedback mechanism to AYS

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-orchestrator#665]
## preparation:

- check https://github.com/zero-os/0-orchestrator/blob/despiegk-specs/specs/feedback_mechanism_ays_service.md
- we need to agree on right mechanism, put right specs in zero-os as well
- check link with zero-os redis ...

**Comment by zaibon** [comment]
Doc related : https://github.com/zero-os/0-core/blob/master/docs/monitoring/logging.md#streams
