### ISSUE TITLE
Bootstrap: authorize new member: Could not connect to remote host

### ISSUE THREAD

**Issue by jvwilder** [zero-os/0-orchestrator#708]
When a node tries to join the network it gets authorized, but then the following error occurs: 
'ERROR - Could not connect to remote host -node ip-' 
Then the node is not longer authorized and this starts over.

**Comment by zaibon** [comment]
Need more information about about the enviroments and the node
@jvwilder  can you add some detail please ?

**Comment by jvwilder** [comment]
Environment:  JS container running Ubuntu 16.04.
Node: in Virtualbox running master version
I tried to reproduce it again and got:
```
[Tue08 11:34] - 25b1e3dc6800d6427e13e9f0731ae1bd.py:139 :j.core.jobcontroller.job.7049f308f7eea1d110678ca663d26278 - INFO     - authorize new member 3632ad6bfa
[Tue08 11:34] - 25b1e3dc6800d6427e13e9f0731ae1bd.py:110 :j.core.jobcontroller.job.7049f308f7eea1d110678ca663d26278 - ERROR    - Could not connect to remote host 192.168.196.190
[Tue08 11:34] - Job.py:66  :j.core.jobcontroller.job.7049f308f7eea1d110678ca663d26278 - INFO     - job job: bootstrap.zero-os!grid1 (bootstrap) done sucessfuly
```
I had the error also couple of times when creating a container on the node that was trying to join the zerotier network.

**Comment by abdulrahmantkhalifa** [comment]
cannot reproduce 
orchestrator version a7fdf8beaff4010177b74dbdacc261e2ef5b0b20
core0 version  677cc71e9fdd82ae682f5e1570cd786158bdfcd0
using qemu to run the nodes as vms

**Comment by Dinaamagdy** [comment]
can't reproduce 
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091
