### ISSUE TITLE
DirectAccess Apis don't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#713]
## steps 
try to get any node info: disks ,processes,jobs,cpus
## Issue 
will result internal server error 
![selection_486](https://user-images.githubusercontent.com/24386802/28246590-f9a194e6-6a1d-11e7-8d7d-71da5a6e07a9.png)

## 0-orchestrator Error : 
```
ERRO[1801] job 'd4009983-4ea9-4025-89c5-51772050e4b0' does not exist 
172.30.222.222 - - [16/Jul/2017:09:56:33 +0000] "GET /nodes/248a07e64220/disks HTTP/1.1" 500 40
```
## Software Version 
master on 7bb604efcd33cf58fd37814389fa3e35a831ee73

**Comment by Dinaamagdy** [comment]
Same for get container jobs and process

**Comment by grimpy** [comment]
When https://github.com/zero-os/0-core/pull/440 gets merged we can update our vendor

**Comment by ahmedelsayed-93** [comment]
### software versions
master :  0675fcc
