### ISSUE TITLE
Use same naming convention for all buildscripts

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#746]
![image](https://user-images.githubusercontent.com/15246294/28560002-3af3fc3e-7119-11e7-959f-5492efa5b5d1.png)

**Comment by serboctor** [comment]
Renamed them to start with `builder` not `build`

**Comment by Dinaamagdy** [comment]
## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091
