### ISSUE TITLE
Rest api: update container nics with put request

### ISSUE THREAD

**Issue by jvwilder** [zero-os/0-orchestrator#765]

**Comment by zaibon** [comment]
AYS service has the support for update but we need to expose this feature over the REST API

**Comment by abdulrahmantkhalifa** [comment]
Only NIC changes are implemented in the process change of the container actions, should I implement other data changes if so, which.

Also concerning this  `AYS service has the support for update but we need to expose this feature over the REST API` isn't it already exposed as execute blueprint  isn't it enough to execute a blueprint with new data to call the process change action, or there other functionality missing .

**Comment by muhamadazmy** [comment]
Actually the only "dynamic" feature of a container that u can update on the fly is NICS, by adding and removing nics. Name, tags, mounts and others are not changeable once the container is started

**Comment by abdulrahmantkhalifa** [comment]
got it thank you

**Comment by Dinaamagdy** [comment]
## Steps 
- make sure that ovc configuration doesn't exist 
- create container without nic 
- use put API to put vlan nic 

## Issue 
it gives right  error in ays  but it give 201 in put request and vlan network added when u get this container: 
```
INFO:network:
[Wed16 14:18] - Job.py              :56  :j.core.jobcontroller.job.64ab5fa3a5c9fc2147491cf751057e2d - ERROR    - Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/5db963e8dc61f38fa3bab5f9bf22429d.py", line 275, in processChange
    update(service, job.logger, job.context['token'], args['nics'])
  File "/tmp/actions/container/5db963e8dc61f38fa3bab5f9bf22429d.py", line 250, in update
    cl.nic_add(container.id, nic_dict)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 1120, in nic_add
    return self._client.json('corex.nic-add', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 726, in json
    result = self.sync(command, arguments, tags=tags, id=id)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 716, in sync
    raise RuntimeError('invalid response: %s' % result.state, result)
RuntimeError: ('invalid response: ERROR', STATE: ERROR
STDOUT:

STDERR:

DATA:
"ovs is needed for VLAN network type"
)
```

## Software Version 
8124cc51afc8f1f6e1431f50e4e83894954e4091

**Comment by abdulrahmantkhalifa** [comment]
@grimpy  
@muhamadazmy 
@Dinaamagdy 
options (i implemented both as instructed):

 - first implementation do the ovs check using  the golang client of core0 to check on containers with tag ovs,  this returns whatever status code i want but completly ignores the ays portion as it is done before the ays blueprint 

 - second implementation check on the status of job if error return message with response of api call to blueprint , the message is error executing blueprint for container mycontainer23 update, the testers are upset with this cause it returns a 500 , which i cannot change so choose

**Comment by abdulrahmantkhalifa** [comment]
this requires a version 8f7faca26027f10bcbdfca859ed3e691f57adcdd

**Comment by Dinaamagdy** [comment]
it return error now ,but the nic added to container nic
## Software version 
e7383bcca187748a6ac6f7e54feb4fa5433e843b

**Comment by Dinaamagdy** [comment]
## Software Version 
c682e501935c720d2c55cfb61ea2d9f8f792c5c2
