### ISSUE TITLE
0-orchestrator flist

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#784]
# Goal 
Make it extremely easy to get started with 0-orchestrator.

# How & requirements
* Create flist with all the 0-orchestrator dependencies, except for jumpscale (See /docs/setup)
* Then merge this flist with the jumpscale 9 flist and ubuntu to produce the flist people need to use
* Buildscript should be easily configurable for specifying versions of dependencies
* Need to have a very simple way to configure variables when running the flist
  * zerotier network
  * itsyouonline org
  * ...
* You need a working Zero-OS running
* Writing a Go program which use Go client to start a 0-orchestrator container and the differents services needed inside the container (caddy, ays, orchestrator)
* Go program needs to be configurable on the runtime

# Deliverables
* flist buildscript
* cli to start container accepting all the needed variables as commandline arguments
* end-user friendly documentation on how to deploy an orchestrator using the orchestrator flist

**Comment by maxux** [comment]
The biggest problem is the configuration which is set during the install/build process, not during the runtime. The best approche would be allowing the configuration to be read during runtime, but this require to change internal things of the orchestrator, etc.
Maybe a temporary solution is to rewrite internal configuration on the runtime but this is will be really hard to maintains.

Eg: during `install-orchestrator.sh`, it's difficult to changes values set on ays, etc. How can we hotchange them on runtime ?

Another solution would create a flist with specific settings inside, but this is against flist-system IMO.
