### ISSUE TITLE
Integrate etcd with 0-disk servers 

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#791]

**Comment by khaledkbadr** [comment]
In the orchestrator current design, we add one tlog server per vm, hence tlogserver are attached to the VM. In 0-disk current implementation, tlogservers seems to act as a cluster in top of the tlog storage cluster and is totally separated from the vm.

I'm putting the task on hold since @grimpy told me he needs to discuss if this is where we should go or not

**Comment by Dinaamagdy** [comment]
## Software Version 
4a360373d205149b7cc0ede1075ce3164f1f6d40

**Comment by Dinaamagdy** [comment]
after run etcd blueprint ,then create storage cluster and vm ,when i login inside Vm get this error : 
![selection_518](https://user-images.githubusercontent.com/24386802/29034899-17c1187e-7b9a-11e7-8b7f-1b7348c246bc.png)

## Software version 
d88cdbeec50e8f5ba4a78b62e12e49823c85f7df
## vdisk request
```
{
  "id": "vdisk2",
  "size": 15,
  "blocksize": 4096,
  "type": "boot",
  "templatevdisk": "ardb://hub.gig.tech:16379/template:ubuntu-1604",
  "readOnly": false,
  "storagecluster": "st1"
}
```

**Comment by Dinaamagdy** [comment]
## Software Version
cc8f872ff3fc1dd158752b98565ed21ab2df5f21
