### ISSUE TITLE
"Timeout reading from socket" error in network stability health check stacktrace

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#801]
### scenario 
- create environment with two nodes
- remove **node_2** (not from the api)
- get **node_1** healthcheck

### result
Error ```TimeoutError: Timeout reading from socket``` 

![image](https://user-images.githubusercontent.com/24386820/28779347-16fdf408-7603-11e7-8517-dfd6a414bd3f.png)

### software version
master : 4768508

**Comment by zaibon** [comment]
Fixed by making sure the healthcheck only runs when we can ping the nodes

**Comment by Dinaamagdy** [comment]
## Software Version 
7c9ffb9d081915770442d3955223406bfaf73f03
