### ISSUE TITLE
Redeploy etcd cluster in case of the current cluster has failed

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#847]
Messages coming from 0-log module in 0-disk that indicate etcd cluster failure, should be handled in watchdog. It should redeploy etcd cluster.

**case1**:  if every single `etcd` server have failed, we don't have the current data that used to be inside them. then re saving the `storage clusters`, `vdisks`, `vms`, `nbdservers`, `tlogservers` config should be in order. the restarting of the `vms` should occur automatically by the `nbdserver` `watchdog_handler`.

**case2**: Only the majority of `etcd` servers have crashed, and some `etcd` servers are alive. This means we have some kind of splitbrain situation and should be handles like case1.

Check: https://github.com/zero-os/0-Disk/blob/master/docs/log.md#broadcasting-to-0-orchestrator

**Comment by khaledkbadr** [comment]
preferably #877 should be done first

**Comment by muhamadazmy** [comment]
@khaledkbadr Why we wait until majority of nodes failed? And why do we have to create a new cluster and move the data around (which as a process can fail and cause permanent loss of data).

I think it's better if watchdog should make sure a new node is added to the cluster once a node crashes, to make sure that etcd always having full number of nodes working.

**Comment by khaledkbadr** [comment]
As I understand the logs coming from 0-Disk would be only if the whole cluster failed and they can't get to the configuration. The watchdog already re-launch the `etcd` server once it crashes, hence I believe the only way that the majority fails that the ZeroOs nodes are failing or the containers are stopping for whatever reason.

**Comment by abdulrahmantkhalifa** [comment]
for Reproduction 
 - **case one** if etcd service died but container is still up, while not passing the n-1/2 threshold 
then the etcd service will just restart again 

 - **case two** if etcd container died, while not passing the n-1/2 threshold 
then the etcd service and container will just restart again
 
 - **case three** if etcd service died but container is still up, while passing the n-1/2 threshold 
then a new cluster will run , the only way to check on this is the service name of the containers and the etcds which will have a new port in the name than the old one 

 - **case  four** if etcd container died, while  passing the n-1/2 threshold 
then a new cluster will run , the only way to check on this is the service name of the containers and the etcds which will have a new port in the name than the old one

**Comment by abdulrahmantkhalifa** [comment]
if failure state , we deploy on the same nodes from the model @grimpy sugggested we use the exisating unassigned nodes, need to discuss with @khaledkbadr and/or @zaibon

**Comment by Dinaamagdy** [comment]
## Steps 
- create 5 nodes 
- create etcd cluster in n1,2,3
- create st in n1 
- delete n2,3
-kill etcd container in n1 
## Issue 
etcd process doesn't return back in any of remain nodes n1,4,5
## Software Version 
6f34ef362b9b602a1179de61a646f954ab65d8b2

**Comment by abdulrahmantkhalifa** [comment]
https://github.com/zero-os/0-orchestrator/pull/971

**Comment by Dinaamagdy** [comment]
## Steps 
- create 5 nodes 
- create etcd cluster in n1,2,3
- create st in n1 
- delete n2,3
-kill etcd service not container in n1 
## Issue 
etcd process  return back in n1 only ,not n2,n3 but if try it by kill etcd container in n1 will return back in three nodes. 
## Software Version 
7bdd6f701d7acd1a918078b737b823752efc8f7a
js9 : 9.1.1

**Comment by rkhamis** [comment]
I just released JS version 9.1.2, which fixes that issue

**Comment by Dinaamagdy** [comment]
## Steps 
- create 5 nodes 
- create etcd cluster in n1,2,3
- create st in n1 
- delete n2,3
- kill etcd service in n1 , it return back in n1,4,5
- kill etcd container in n1 or n4
## Issue 
etcd process doesn't  return back for 10 min  althought the watchdog handler is working 
```
job job: etcd_cluster!myetcd (watchdog_handler) done sucessfuly
```

**Comment by Dinaamagdy** [comment]
## scenarios : 
1- create 5 nodes 
2- create etcd cluster for n1,2,3 
3- kill etcd process for n1 ,should return back 
4- kill etcd container for n2.should return back 
5- delete n2,3
6- kill etcd service in n1 , it return back in n1,4,5
7- kill etcd container in n4 or n1 or n5 , should return back 

## another scenario:
1- create 5 nodes 
2- create etcd cluster for n1,2,3 
3- kill etcd container for n1 ,should return back 
4- kill etcd process  for n2.should return back 
5- delete n2,3
6- kill etcd container  in n1 , it return back in n1,4,5
7- kill etcd service in n4 or n1 or n5 , should return back

**Comment by Dinaamagdy** [comment]
## Software Version 
0f2b740a128402caf085a0408be5c4686b8ee210
