### ISSUE TITLE
Orch installation scrip provides wrong running port

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#855]
**Steps**
- Use the installation script to install orch 
- It says that orch is working in port 443 however its should be working in port 8080

**Version**
alpha-7

**Comment by grimpy** [comment]
Talked to Islam he claims that the orchestrator is not accessible on the 443 (caddy)

**Comment by ashraffouda** [comment]
this happened because u don't have a domain so caddy didn't issue a certificate for u and instead it provide  a self signed on which u should accept first for ur requests to work

**Comment by Dinaamagdy** [comment]
##  Software Version 
337169e32a2e4d28fb06178c06c6d93d2e4c47c0
