### ISSUE TITLE
orch installation script use the same branch name to install core-0 and orch clients

### ISSUE THREAD

**Issue by islamTaha12** [zero-os/0-orchestrator#858]
https://github.com/zero-os/0-orchestrator/blob/master/scripts/install-orchestrator.sh#L93

**Description:**
Install script should take two branches parameters, one for orch client and the other for the core-0 client. Because if u have a branch in orch with the name of "Fix_issue_xx" and for sure there is no branch with this name in core-0, the installation script won't work as expected.

**Version**
master

**Comment by islamTaha12** [comment]
![image](https://user-images.githubusercontent.com/17981089/29173677-6bc5bc30-7de4-11e7-8089-fd09e6cc0b38.png)

**Comment by maxux** [comment]
This is the expected behavior I think.
You need to specify at least: `<BRANCH> <ZEROTIERNWID> <ZEROTIERTOKEN> <ITSYOUONLINEORG>`
This is for backward compatibility?

**Comment by maxux** [comment]
Please test with: https://github.com/zero-os/0-orchestrator/commit/e54f538f1941333c03d49f126117dd81c1461bb5
