### ISSUE TITLE
Cannot create two influx databases on the same node from ays

### ISSUE THREAD

**Issue by mie00** [zero-os/0-orchestrator#864]
Influxdb uses [two ports](https://docs.influxdata.com/influxdb/v1.3/introduction/installation/#networking) one of them is configurable through ays and the other is not. So creating a service even with a different port fails at creating the second service because the other port (8088) is already in use.

**Comment by Dinaamagdy** [comment]
## Software Version 
96700d6f42264111ba2d06cea4dfce6d29aff13b
