### ISSUE TITLE
Installation of a storage cluster fails

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#866]
Blueprint used :

```yaml
- action: install
  actor: storage_cluster
  service: mycluster
  force: false
storage_cluster__mycluster:
  label: mycluster
  nrServer: 56
  diskType: ssd
  nodes:
   - 0cc47a3aad5a
   - 0cc47a3b3d6a
   - 0cc47a3b3d98
   - 0cc47a3b3eb2
   - 0cc47a6b2c1c
   - 0cc47aab6444
   - 0cc47aab6702
   - 0cc47aab670a
  clusterType: storage
  k: 0
  m: 0
```

First time execute the blueprint I get:
```
 ays blueprint storage.bp
[Thu10 14:41] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
error during execution of the blueprint storage.bp: Error: Request Timeout
```

Then second time I try to execute the blueprint it works. but then when I create the run.
The init action of the storagecluster is schedule. Which shouldn't be the case, cause init is supposed to be executed during the execution of the blueprint.

I tried to run the blueprint anyway but got this error:
```
2017/08/10 14:51:25 trace: JumpScale9.errorhandling.JSExceptions.Input: ERROR: Not enough available disks on node 0cc47aab670a ((type:input.error)
        
        
        
         2017/08/10 14:51:25 errormsg: Traceback (most recent call last):
          File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/tmp/actions/storage_cluster/a228ca9d02447f177e5ed702330713ee.py", line 75, in init
            raise j.exceptions.Input("Not enough available disks on node {}".format(node.name))
        JumpScale9.errorhandling.JSExceptions.Input: ERROR: Not enough available disks on node 0cc47aab670a ((type:input.error)
```

Which clearly show that the init has not been executed the first time cause this error is supposed to be raise during the blueprint executing not during the run.

**Comment by zaibon** [comment]
probably duplicate of #691

**Comment by islamTaha12** [comment]
we created 10 nodes type 2 and we tried to create a storage cluster, It consumed more than 15mins and of course the api request return time out then we listed the cluster, it returned the cluster name then we get the cluster status, it returned 500 then we tried to create vdisk, it consumed +3mins and return 500

**Comment by zaibon** [comment]
Should be fix by https://github.com/Jumpscale/ays9/pull/168

**Comment by islamTaha12** [comment]
verified.
We created a storage cluster in 5 nodes (25 ssd disk), it consumed ~400sec. Then we get the cluster info, it consumed ~90sec
