### ISSUE TITLE
Make etcd listen on both mgmt and storage network

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-orchestrator#877]
At the moment, to push data to `etcd` cluster we pick random `etcd` service and use it to push the data to the whole cluster. And this approach is risky since that etcd maybe down. Alternatively if etcd servers listened to the mgmt network then we can push data to it using the etcd python/golang package directly without the need for `etcdctl` binary

**Comment by khaledkbadr** [comment]
Looks like the `python-etcd`  package isn't stable with `etcd` v3, therefore I will close this issue to brainstorm and find better solution

**Comment by khaledkbadr** [comment]
Looks like https://github.com/kragniz/python-etcd3 is good option to investigate. So I'm gonna reopen this issue for investigation

**Comment by grimpy** [comment]
Khaled figured out that the above python client does not take a cluster into consideration so using that specific client doesnt help the current situation.

**Comment by grimpy** [comment]
We could just use the one that supports connecting to a single node and loop over the servers from the ays code instead.

**Comment by Dinaamagdy** [comment]
## Software Version 
112ce78e9924585b2bed71c4fdf87df6db2f1c57
