### ISSUE TITLE
Get non-existing vm info returns 500 instead of 404

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-orchestrator#878]
### API
```GET  /nodes/{nodeid}/vms/{vmid}/info ```

![image](https://user-images.githubusercontent.com/24386820/29272082-de8dc344-80fe-11e7-8385-e30e18f15ea5.png)

### software version
1.1.0-alpha-7 : e86e4f1

**Comment by Dinaamagdy** [comment]
## Software Version 
108e1ac0d6769d5dc65b2ca20503d8b22ea5f40c
