### ISSUE TITLE
unexpected error in Orch installation script

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#882]
use orch installation script  as in docs here : https://github.com/zero-os/0-orchestrator/tree/master/docs/setup
it produce this error : 
```
[-] line 56: unexpected error
```

**Comment by grimpy** [comment]
Pleasre provide errors from the logs

**Comment by Dinaamagdy** [comment]
there is  no logs for this state,error happen when you didn't  add 
```
--core0 master
```
which should be option

**Comment by Dinaamagdy** [comment]
## Software Version 
6f34ef362b9b602a1179de61a646f954ab65d8b2

**Comment by Dinaamagdy** [comment]
## Software Version 
6f34ef362b9b602a1179de61a646f954ab65d8b2
