### ISSUE TITLE
RESTful API call fails because of JWT expiring DURING executing 

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-orchestrator#888]
During a demo we had a JWT that was valid and accepted at the start of a RESTful API call but expired during execution, as a result the execution failed

**Comment by grimpy** [comment]
Please provide full scenario how JWT was used and which APIs/calls where made

**Comment by yveskerwyn** [comment]
We can close this it will be solved by https://github.com/zero-os/0-orchestrator/issues/905
