### ISSUE TITLE
Protect Orchestrator API with different JWT then the one of AYS Server

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-orchestrator#889]
Currently you get both access to the Orchestrator API AND the AYS Server with the same JWT, which should not be allowed, the AYS Server RESTful API should be protected for internal use only.

This is maybe also why we had the problem described in https://github.com/zero-os/0-orchestrator/issues/888

**Comment by grimpy** [comment]
This is not possible by design. Because the orchestrator forwards the JWT of the client towards the AYS server which by itself forwards it to the zero-os nodes.
