### ISSUE TITLE
Create AYS template for 0-stor server

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-orchestrator#895]
In this milestone the tlog will change its backend to use https://github.com/zero-os/0-stor instead of ardb. 

We need to create an AYS template and logic in the SAL to deploy the 0-stor servers during the installation of the storage infrastructure.

Requirements :
- [x] tlog AYS template
- [x] Logic in SAL to deploy the 0-stor on top of disk like we do for arbd

**Comment by Dinaamagdy** [comment]
## Software Version 
112ce78e9924585b2bed71c4fdf87df6db2f1c57
