### ISSUE TITLE
KeyError while trying to update a container nic

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#910]
**With default option , id is not required**

![sccccc0](https://user-images.githubusercontent.com/15011431/29750152-042fc9da-8b3b-11e7-99e6-328717945a8c.png)

![sccc](https://user-images.githubusercontent.com/15011431/29750153-059a9110-8b3b-11e7-969b-4b3f25ca68c6.png)

**Comment by Dinaamagdy** [comment]
## Software Version 
c682e501935c720d2c55cfb61ea2d9f8f792c5c2
