### ISSUE TITLE
Monitor action for node stops working 

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#936]
## Steps 
- create storage cluster on node 
- stop node 
## Issue
use api ```  get node ``` you will find node still running , and check ays u will find that monitor action stops . 

## Software Version
b0e3a55280d82a3d97c68bb3494739a69bc292a3

**Comment by khaledkbadr** [comment]
Can't reproduce

**Comment by ahmedelsayed-93** [comment]
Can't reproduce

### software version
master 5c7668358
