### ISSUE TITLE
Reboot api call to 0-orchestrator rest server does not work

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-orchestrator#942]
Geert Audenaert, [01.09.17 14:31]
trying to reboot a node via the orchestrator

Geert Audenaert, [01.09.17 14:31]
does not seem to work

Geert Audenaert, [01.09.17 14:31]
reboot is not happening

Geert Audenaert, [01.09.17 14:32]
no errors, nor stacktraces

Christophe de Carvalho, [01.09.17 14:32]
packet.net?

Geert Audenaert, [01.09.17 14:32]
no, a threefold node

Geert Audenaert, [01.09.17 14:32]
and this makes it  blocker

Christophe de Carvalho, [01.09.17 14:32]
:/

Geert Audenaert, [01.09.17 14:34]
we need to be able to reboot the nodes from centrally

Jo De Boeck, [01.09.17 14:35]
[Antwoord op Geert Audenaert]
Any other action happening?

Jo De Boeck, [01.09.17 14:35]
[Antwoord op Geert Audenaert]
Proper reboot is planned for beta1 though

Jo De Boeck, [01.09.17 14:36]
At least proper restoration of running services

Geert Audenaert, [01.09.17 15:18]
[Antwoord op Jo De Boeck]
Nothing happens apart from getting a nice 204

Christophe de Carvalho, [01.09.17 15:18]
Did you tried manually with the python client?

Geert Audenaert, [01.09.17 15:25]
Yes, just did that now

Geert Audenaert, [01.09.17 15:25]
And that works perfectly

Geert Audenaert, [01.09.17 15:26]
Very strange

Jo De Boeck, [01.09.17 15:27]
Hmm would the direct API be broken again for a change?

Geert Audenaert, [01.09.17 15:27]
No, it actually goes through AYS

Geert Audenaert, [01.09.17 15:27]
https://github.com/zero-os/0-orchestrator/blob/master/templates/node.zero-os/actions.py#L231

Geert Audenaert, [01.09.17 15:27]
I can see the logs in the tmux

**Comment by muhamadazmy** [comment]
I tried it multiple times and could not reproduce

**Comment by ahmedelsayed-93** [comment]
can't reproduce 

### software version 
master : 851d41fa
