### ISSUE TITLE
Broken installation because of a jwt error

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#946]
![sc3](https://user-images.githubusercontent.com/15011431/30019901-5c94d87c-9162-11e7-84b1-5e0b58b6cfe5.png)

## Note
Most probably the jose version need to be changed from '1.4.0' --> '1.3.2'

**Comment by rkhamis** [comment]
Should be fixed in https://github.com/Jumpscale/ays9/commit/1aa806aab67ba446b5079bf891c09bdcd7525604
