### ISSUE TITLE
Health check status  for node ok,although node status is halted

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-orchestrator#950]
## Issue 
node status is halted, but when you check node health check , you will find it ok as shown : 
![selection_525](https://user-images.githubusercontent.com/24386802/30028327-edf315f0-9184-11e7-91b8-15ff7e2db7f0.png)
![selection_526](https://user-images.githubusercontent.com/24386802/30028350-fed10ada-9184-11e7-851a-71998a65f08a.png)
## Software Version 
0d238efa01e6f8ee291f2d3cec4d1e918aa39212

**Comment by ahmedelsayed-93** [comment]
### software version
master : 5c7668358
