### ISSUE TITLE
Investigation Needed

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-orchestrator#968]
**These test cases are totally working fine, they are just failing in travis .. 
suggestion: if we can't find what are the errors, we need at some point to be able to print the logs in the ays so we can understand why these errors are happening**  

======================================================================

FAIL: GAT-085

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/zero-os/0-orchestrator/tests/0_orchestrator/test_suite/testcases/extend_tests/test01_containers_apis.py", line 124, in test004_create_containers_with_different_flists

    self.assertEqual(self.response.status_code, 201, " [*] Can't create new container.")

AssertionError: 500 != 201 :  [*] Can't create new container.

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: http://10.147.17.126:8080 "GET /nodes HTTP/1.1" 200 195

[secure]: INFO: Get random nodeid : 0cc47ad66770

g8core: DEBUG: 5c652da3-806e-49a4-ae2b-a6fe208fa0e8 >> g8core.core.ping()

g8core: DEBUG: 5c652da3-806e-49a4-ae2b-a6fe208fa0e8 << SUCCESS, stdout="", stderr="", data=""PONG Version: master @Revision: ec56dc32841d4a54990289bc3266866230690395""

[secure]: INFO:  [*] Create new container. 

urllib3.connectionpool: DEBUG: http://10.147.17.126:8080 "POST /nodes/0cc47ad66770/containers HTTP/1.1" 500 66

[secure]: INFO: TearDown:delete all created containers and bridges

--------------------- >> end captured logging << ---------------------

======================================================================

FAIL: GAT-087

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/zero-os/0-orchestrator/tests/0_orchestrator/test_suite/testcases/extend_tests/test01_containers_apis.py", line 209, in test006_create_container_with_bridge

    self.assertEqual(response.state, 'SUCCESS')

AssertionError: 'ERROR' != 'SUCCESS'

- ERROR

+ SUCCESS
--------------------------------------------------------------------------------------------------
======================================================================

FAIL: GAT-096

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/zero-os/0-orchestrator/tests/0_orchestrator/test_suite/testcases/extend_tests/test01_containers_apis.py", line 693, in test015_create_containers_with_open_ports

    self.assertEqual(response.state, 'SUCCESS')

AssertionError: 'ERROR' != 'SUCCESS'

- ERROR

+ SUCCESS

**Comment by Dinaamagdy** [comment]
working in FAIL: GAT-085

**Comment by Dinaamagdy** [comment]
GAT-085 done https://github.com/zero-os/0-orchestrator/pull/969/commits/cfa01f208a32c185aae4d3b3aaa064d70b97bb28

**Comment by john-kheir** [comment]
Need to be investigated
```
======================================================================

FAIL: GAT-089

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/zero-os/0-orchestrator/tests/0_orchestrator/test_suite/testcases/basic_tests/test10_containers_apis_ext.py", line 327, in test008_Create_container_with_zerotier_network

    self.assertEqual(response.state, "SUCCESS")

AssertionError: 'ERROR' != 'SUCCESS'

- ERROR

+ SUCCESS
```

**Comment by john-kheir** [comment]
It was all errors related to the testsuite: https://github.com/zero-os/0-orchestrator/pull/1009
